### ISSUE TITLE
fix problem where requested images are repeated

### ISSUE THREAD

**Issue by juniorbotelho** [juniorbotelho/slidemaker.js#31]

**Comment by LuisFernandoPeretti** [comment]
amigo, você subistituiu a api do algorithmia pela do wikipedia?
desculpa a pergunta, é que olhei seu projeto e vi que ainda existe documentos do algorithmia e, como ainda não tenho muita experiência, não consegui interpretar se você ainda está utitilizando-a ou não.
obrigado

**Comment by juniorbotelho** [comment]
@LuisFernandoPeretti Eu não uso mais o algorithmia nesse projeto (apesar de ainda está implementado), eu uso a própria API pública do **Wikipédia**, você pode ver ela aqui: [juniorbotelho/videmaker-core/wikipedia](https://github.com/juniorbotelho/videomaker-core/blob/main/utilities/Wikipedia.ts)

**Comment by EvandAraujo** [comment]
Olá, Eu vi que voce parou foi um dos ultimos a continuar o projeto, eu estou disposto a continuar, se voce quiser, podemos montar um grupo no slack ou no discord para dar andamento nesse projeto.

**Comment by juniorbotelho** [comment]
Opah! Olá @EvandAraujo, tranquilo? 👋

Eu decidi pausar o projeto devido às minhas outras tarefas, além disso, no caso desse projeto, eu ainda preciso resolver muitos problemas, como a arquitetura que não ficou tão boa quanto deveria, e também preciso remover uma boa parte das bibliotecas que no momento são dispensáveis. Mas pode compartilhar conosco a tua ideia, caso seja interessante a gente pode dar continuidade sim. Abraços!
